[litepanel-admin]
enabled = True
port = 2087
filter = sshd
logpath = /var/log/litepanel/admin-error.log
maxretry = 5

[litepanel-user]
enabled = True
port = 2083
filter = sshd
logpath = /var/log/litepanel/user-error.log
maxretry = 5
