[litepanel-admin]
enabled = True
port = 2087
filter = litepanel
logpath = /var/log/litepanel/admin-error.log
maxretry = 3
findtime = 600
bantime = 3600

[litepanel-user]
enabled = True
port = 2083
filter = litepanel
logpath = /var/log/litepanel/user-error.log
maxretry = 3
findtime = 600
bantime = 3600
